definitions:
  models.AddUser:
    properties:
      email:
        example: jumaniyozovibodulla07@gmail.com
        type: string
      language:
        enum:
        - uz
        - ' ru'
        - ' en'
        type: string
      name:
        example: Jumaniyozov Ibodulla
        type: string
      password_hash:
        example: PASSWORD_HASH
        type: string
    type: object
  models.GetAllUsersResponse:
    properties:
      count:
        type: integer
      users:
        items:
          $ref: '#/definitions/models.GetUser'
        type: array
    type: object
  models.GetUser:
    properties:
      created_at:
        type: string
      email:
        example: jumaniyozovibodulla07@gmail.com
        type: string
      id:
        example: 9c1242b2-b211-4a91-ba6c-a58e903327fd
        type: string
      language:
        enum:
        - uz
        - ' ru'
        - ' en'
        type: string
      name:
        example: Jumaniyozov Ibodulla
        type: string
    type: object
  models.Response:
    properties:
      data: {}
      description:
        type: string
      statusCode:
        type: integer
    type: object
  models.SeccessRequest:
    properties:
      code:
        type: string
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: STAR FLOW PRO BACKEND
  version: "1.0"
paths:
  /api/v1/user:
    post:
      consumes:
      - application/json
      description: This api CREATE AN USER
      parameters:
      - description: USER INFO
        in: body
        name: users
        required: true
        schema:
          $ref: '#/definitions/models.AddUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.SeccessRequest'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
      security:
      - ApiKeyAuth: []
      summary: CREATE AN USER
      tags:
      - USERS
  /api/v1/user/{id}:
    delete:
      consumes:
      - application/json
      description: THIS API DELETE AN USER
      parameters:
      - description: USER ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.SeccessRequest'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
      security:
      - ApiKeyAuth: []
      summary: DELETE AN USER
      tags:
      - USERS
  /api/v1/users:
    get:
      consumes:
      - application/json
      description: THIS API GET ALL USERS
      parameters:
      - description: Search BY FULL NAME
        in: query
        name: search_by_full_name
        type: string
      - description: Search BY USERNAME
        in: query
        name: search_by_username
        type: string
      - description: Search BY ID
        in: query
        name: search_by_id
        type: integer
      - description: page
        in: query
        name: page
        type: integer
      - description: limit
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GetAllUsersResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
      security:
      - ApiKeyAuth: []
      summary: GET ALL USERS
      tags:
      - USERS
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
